spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: lb://CUSTOMER-SERVICE
          predicates:
            Path= /api/customers/**
        - id: r2
          uri: lb://INVENTORY-SERVICE
          predicates:
            Path= /api/products/**

#    gateway:
#      mvc:
#        routes:
#          - id : r1
#            uri:  http://localhost:9081
#            predicates:
#              - Path= /customers/**
#          - id: r2
#            uri: http://localhost:9082
#            predicates:
#              - Path= /products/**
#    gateway:
#      routes:
#        - id: r1
#          uri: http://localhost:8081
#          predicates:
#            - Path= /customers/**
#        - id: r2
#          uri: http://localhost:8082
#          predicates:
#            - Path= /products/**
#




      globalcors:
        corsConfigurations:
          '[/**]': # Applique la configuration CORS à toutes les routes
            allowedOrigins: "http://localhost:4200" # Origine Angular
            allowedHeaders: "*" # Autorise tous les en-têtes
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
